/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "log.h"
/* Header for class com_example_test_MainActivity */

#ifndef _Included_com_example_test_MainActivity
#define _Included_com_example_test_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_MainActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_MainActivity_sayHello
  (JNIEnv *, jobject);


/*
 * Class:     com_example_test_MainActivity
 * Method:    createThradPool
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_test_MainActivity_createThradPool
        (JNIEnv *, jobject);



JNIEXPORT void JNICALL Java_com_example_test_MainActivity_threadAdd
        (JNIEnv *, jobject, jint, jintArray);

/**
 * 销毁线程池
 */
JNIEXPORT void JNICALL Java_com_example_test_MainActivity_thradDestory
        (JNIEnv *, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
